In [2]:
import os
import sys

sys.path.insert(0, os.path.abspath('..'))

In [3]:
import src.graphs as graphs
import src.load as load
import src.table as table
import app.paths as paths

In [4]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [5]:
meta, y, t_weeks, idx_dict, total_kg = load.load_historical_data()

In [ ]:
year = 2023

In [12]:
szn_act = table.shift_actuals(y.values,t_weeks)

In [13]:
idx = idx_dict['year'][year]

In [14]:
fig = graphs.season_act_graph(meta,szn_act,idx,'Actual')

In [ ]:
fig.show() # add annotation for how much yield is made for each part

In [39]:
df = pd.DataFrame(szn_act[idx].sum(axis=0)[:53], columns=['kg'])
df.index.name = 'week of season'
ha_table = meta[idx].groupby('transplant_week').agg({'ha':'sum'}).T

In [41]:
df.T.astype(int)

week of season,0,1,2,3,4,5,6,7,8,9,...,43,44,45,46,47,48,49,50,51,52
kg,0,0,0,0,0,0,0,0,0,0,...,30234,50712,29430,29809,28735,23867,17116,15462,10439,0

In [42]:
ha_table

transplant_week,10,11,13,14,15,16,17,18,19,20,...,23,25,26,27,28,29,31,32,33,37
ha,1.92,3.4892,5.3546,5.6183,0.44,2.8716,4.464,3.394,7.6335,0.6225,...,0.3264,4.178,2.1327,2.6725,3.0287,0.26,6.1858,5.464,1.767,1.4976